# Generated by Django 5.2.4 on 2025-08-01 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Заводской номер')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('production_date', models.DateField(verbose_name='Дата изготовления')),
                ('commissioning_date', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Место установки')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='Ответственное лицо')),
                ('status', models.CharField(choices=[('in_operation', 'В эксплуатации'), ('repair', 'В ремонте'), ('reserve', 'В резерве'), ('decommissioned', 'Списано')], default='in_operation', max_length=20, verbose_name='Статус')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name='Фото оборудования')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passports.equipmenttype', verbose_name='Тип оборудования')),
            ],
        ),
    ]
