# Generated by Django 5.2.5 on 2025-08-22 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_remove_equipmentpassport_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentpassport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='equipmentpassport',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пользовательские поля'),
        ),
        migrations.AddField(
            model_name='equipmentpassport',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passports.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipmentpassport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MaintenanceWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('repair', 'Ремонт'), ('maintenance', 'Техническое обслуживание'), ('diagnostic', 'Диагностика'), ('inspection', 'Осмотр'), ('calibration', 'Калибровка')], max_length=20, verbose_name='Тип работы')),
                ('work_date', models.DateField(verbose_name='Дата выполнения')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='Ответственное лицо')),
                ('description', models.TextField(blank=True, verbose_name='Описание работы')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('materials_used', models.TextField(blank=True, verbose_name='Использованные материалы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные параметры')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_works', to='passports.equipmentpassport')),
            ],
            options={
                'ordering': ['-work_date'],
            },
        ),
    ]
